/*
 * This file is generated by jOOQ.
 */
package club.koumakan.web.framework.dsl.tables.records;


import club.koumakan.web.framework.dsl.tables.DataDictionary;
import org.jooq.*;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
  value = {
    "http://www.jooq.org",
    "jOOQ version:3.12.3"
  },
  comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class DataDictionaryRecord extends UpdatableRecordImpl<DataDictionaryRecord> implements Record4<Long, String, String, JSONB> {

  private static final long serialVersionUID = 392359216;

  /**
   * Create a detached DataDictionaryRecord
   */
  public DataDictionaryRecord() {
    super(DataDictionary.DATA_DICTIONARY);
  }

  /**
   * Create a detached, initialised DataDictionaryRecord
   */
  public DataDictionaryRecord(Long id, String code, String name, JSONB data) {
    super(DataDictionary.DATA_DICTIONARY);

    set(0, id);
    set(1, code);
    set(2, name);
    set(3, data);
  }

  /**
   * Getter for <code>public.data_dictionary.id</code>.
   */
  public Long getId() {
    return (Long) get(0);
  }

  /**
   * Setter for <code>public.data_dictionary.id</code>.
   */
  public void setId(Long value) {
    set(0, value);
  }

  /**
   * Getter for <code>public.data_dictionary.code</code>.
   */
  public String getCode() {
    return (String) get(1);
  }

  /**
   * Setter for <code>public.data_dictionary.code</code>.
   */
  public void setCode(String value) {
    set(1, value);
  }

  /**
   * Getter for <code>public.data_dictionary.name</code>.
   */
  public String getName() {
    return (String) get(2);
  }

  /**
   * Setter for <code>public.data_dictionary.name</code>.
   */
  public void setName(String value) {
    set(2, value);
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  /**
   * Getter for <code>public.data_dictionary.data</code>.
   */
  public JSONB getData() {
    return (JSONB) get(3);
  }

  // -------------------------------------------------------------------------
  // Record4 type implementation
  // -------------------------------------------------------------------------

  /**
   * Setter for <code>public.data_dictionary.data</code>.
   */
  public void setData(JSONB value) {
    set(3, value);
  }

  @Override
  public Record1<Long> key() {
    return (Record1) super.key();
  }

  @Override
  public Row4<Long, String, String, JSONB> fieldsRow() {
    return (Row4) super.fieldsRow();
  }

  @Override
  public Row4<Long, String, String, JSONB> valuesRow() {
    return (Row4) super.valuesRow();
  }

  @Override
  public Field<Long> field1() {
    return DataDictionary.DATA_DICTIONARY.ID;
  }

  @Override
  public Field<String> field2() {
    return DataDictionary.DATA_DICTIONARY.CODE;
  }

  @Override
  public Field<String> field3() {
    return DataDictionary.DATA_DICTIONARY.NAME;
  }

  @Override
  public Field<JSONB> field4() {
    return DataDictionary.DATA_DICTIONARY.DATA;
  }

  @Override
  public Long component1() {
    return getId();
  }

  @Override
  public String component2() {
    return getCode();
  }

  @Override
  public String component3() {
    return getName();
  }

  @Override
  public JSONB component4() {
    return getData();
  }

  @Override
  public Long value1() {
    return getId();
  }

  @Override
  public String value2() {
    return getCode();
  }

  @Override
  public String value3() {
    return getName();
  }

  @Override
  public JSONB value4() {
    return getData();
  }

  @Override
  public DataDictionaryRecord value1(Long value) {
    setId(value);
    return this;
  }

  @Override
  public DataDictionaryRecord value2(String value) {
    setCode(value);
    return this;
  }

  @Override
  public DataDictionaryRecord value3(String value) {
    setName(value);
    return this;
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  @Override
  public DataDictionaryRecord value4(JSONB value) {
    setData(value);
    return this;
  }

  @Override
  public DataDictionaryRecord values(Long value1, String value2, String value3, JSONB value4) {
    value1(value1);
    value2(value2);
    value3(value3);
    value4(value4);
    return this;
  }
}
