/*
 * This file is generated by jOOQ.
 */
package club.koumakan.web.framework.dsl.tables.records;


import club.koumakan.web.framework.dsl.tables.Role;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.processing.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
  value = {
    "http://www.jooq.org",
    "jOOQ version:3.12.3"
  },
  comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class RoleRecord extends UpdatableRecordImpl<RoleRecord> implements Record3<Long, String, String> {

  private static final long serialVersionUID = 461270678;

  /**
   * Create a detached RoleRecord
   */
  public RoleRecord() {
    super(Role.ROLE);
  }

  /**
   * Create a detached, initialised RoleRecord
   */
  public RoleRecord(Long id, String name, String code) {
    super(Role.ROLE);

    set(0, id);
    set(1, name);
    set(2, code);
  }

  /**
   * Getter for <code>public.role.id</code>.
   */
  public Long getId() {
    return (Long) get(0);
  }

  /**
   * Setter for <code>public.role.id</code>.
   */
  public void setId(Long value) {
    set(0, value);
  }

  /**
   * Getter for <code>public.role.name</code>.
   */
  public String getName() {
    return (String) get(1);
  }

  /**
   * Setter for <code>public.role.name</code>.
   */
  public void setName(String value) {
    set(1, value);
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  /**
   * Getter for <code>public.role.code</code>.
   */
  public String getCode() {
    return (String) get(2);
  }

  // -------------------------------------------------------------------------
  // Record3 type implementation
  // -------------------------------------------------------------------------

  /**
   * Setter for <code>public.role.code</code>.
   */
  public void setCode(String value) {
    set(2, value);
  }

  @Override
  public Record1<Long> key() {
    return (Record1) super.key();
  }

  @Override
  public Row3<Long, String, String> fieldsRow() {
    return (Row3) super.fieldsRow();
  }

  @Override
  public Row3<Long, String, String> valuesRow() {
    return (Row3) super.valuesRow();
  }

  @Override
  public Field<Long> field1() {
    return Role.ROLE.ID;
  }

  @Override
  public Field<String> field2() {
    return Role.ROLE.NAME;
  }

  @Override
  public Field<String> field3() {
    return Role.ROLE.CODE;
  }

  @Override
  public Long component1() {
    return getId();
  }

  @Override
  public String component2() {
    return getName();
  }

  @Override
  public String component3() {
    return getCode();
  }

  @Override
  public Long value1() {
    return getId();
  }

  @Override
  public String value2() {
    return getName();
  }

  @Override
  public String value3() {
    return getCode();
  }

  @Override
  public RoleRecord value1(Long value) {
    setId(value);
    return this;
  }

  @Override
  public RoleRecord value2(String value) {
    setName(value);
    return this;
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  @Override
  public RoleRecord value3(String value) {
    setCode(value);
    return this;
  }

  @Override
  public RoleRecord values(Long value1, String value2, String value3) {
    value1(value1);
    value2(value2);
    value3(value3);
    return this;
  }
}
