/*
 * This file is generated by jOOQ.
 */
package club.koumakan.web.framework.dsl;


import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all sequences in public
 */
@Generated(
  value = {
    "http://www.jooq.org",
    "jOOQ version:3.12.3"
  },
  comments = "This class is generated by jOOQ"
)
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Sequences {

  /**
   * The sequence <code>public.data_dictionary_id_seq</code>
   */
  public static final Sequence<Long> DATA_DICTIONARY_ID_SEQ = new SequenceImpl<Long>("data_dictionary_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

  /**
   * The sequence <code>public.log_id_seq</code>
   */
  public static final Sequence<Long> LOG_ID_SEQ = new SequenceImpl<Long>("log_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

  /**
   * The sequence <code>public.role_id_seq</code>
   */
  public static final Sequence<Long> ROLE_ID_SEQ = new SequenceImpl<Long>("role_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

  /**
   * The sequence <code>public.user_id_seq</code>
   */
  public static final Sequence<Long> USER_ID_SEQ = new SequenceImpl<Long>("user_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
